spring:
  application:
    name: NextGen Seamless Upgrade

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: vijay
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

app:
  ansible:
    playbooks-directory: /

springdoc:
  swagger-ui:
    path: /swagger-ui.html